/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

import conexao.Conexao;
 
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.sql.*;
import javax.swing.table.DefaultTableModel;

public class Frm_Servicos extends javax.swing.JInternalFrame {

    Conexao con_cliente;
    public Frm_Servicos() {
        initComponents();
        con_cliente = new Conexao(); // inicialização do objeto como instância
        con_cliente.conecta(); // chama o método que conecta
        con_cliente.executaSQL("select * from servicos order by Cod_Servico");
        preencherTabela();
        posicionarRegistro();
        tblServicos.setAutoCreateRowSorter(true); // ativa a classificação ordenada da tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_panel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        txttiposervico = new javax.swing.JTextField();
        lbl_codigotiposervico = new javax.swing.JLabel();
        lbl_codigoservico = new javax.swing.JLabel();
        lbl_codigoagendamento = new javax.swing.JLabel();
        txtcodagendam = new javax.swing.JTextField();
        txtnomeservico = new javax.swing.JTextField();
        lbl_nomeservico = new javax.swing.JLabel();
        btn_registro = new javax.swing.JButton();
        btn_gravar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        scp_tabela = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        btn_primeiro = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        lbl_pesquisar = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        txtcodservico = new javax.swing.JLabel();
        btn_sair1 = new javax.swing.JButton();
        lbl_imagem = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2362, 1055));
        setMinimumSize(new java.awt.Dimension(2362, 1055));
        setPreferredSize(new java.awt.Dimension(2362, 1055));
        getContentPane().setLayout(null);

        pnl_panel1.setMinimumSize(new java.awt.Dimension(32767, 32767));
        pnl_panel1.setPreferredSize(new java.awt.Dimension(32767, 32767));

        lbl_titulo.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        lbl_titulo.setText("CADASTRO SERVIÇOS");

        lbl_codigotiposervico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_codigotiposervico.setText("Código Tipo Serviço:");

        lbl_codigoservico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_codigoservico.setText("Código Serviço:");

        lbl_codigoagendamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_codigoagendamento.setText("Código Agendamento:");

        lbl_nomeservico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nomeservico.setText("Nome Serviço:");

        btn_registro.setBackground(new java.awt.Color(153, 204, 255));
        btn_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registro.setText("Novo Registro");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        btn_gravar.setBackground(new java.awt.Color(153, 204, 255));
        btn_gravar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_gravar.setText("Gravar");
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(153, 204, 255));
        btn_alterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(153, 204, 255));
        btn_excluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(153, 204, 255));
        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        tblServicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblServicos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Serviço", "Código Tipo Serviço ", "Código Agendamento", "Nome Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicosMouseClicked(evt);
            }
        });
        tblServicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblServicosKeyPressed(evt);
            }
        });
        scp_tabela.setViewportView(tblServicos);

        btn_primeiro.setBackground(new java.awt.Color(153, 204, 255));
        btn_primeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_primeiro.setText("Primeiro");
        btn_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeiroActionPerformed(evt);
            }
        });

        btn_anterior.setBackground(new java.awt.Color(153, 204, 255));
        btn_anterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_proximo.setBackground(new java.awt.Color(153, 204, 255));
        btn_proximo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_proximo.setText("Próximo");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        btn_ultimo.setBackground(new java.awt.Color(153, 204, 255));
        btn_ultimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ultimo.setText("Último");
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        lbl_pesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_pesquisar.setText("Pesquisar nome do serviço:");

        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        btn_sair1.setBackground(new java.awt.Color(153, 204, 255));
        btn_sair1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sair1.setText("Sair");
        btn_sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_panel1Layout = new javax.swing.GroupLayout(pnl_panel1);
        pnl_panel1.setLayout(pnl_panel1Layout);
        pnl_panel1Layout.setHorizontalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_codigotiposervico)
                        .addGap(53, 53, 53)
                        .addComponent(txttiposervico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_codigoagendamento)
                            .addComponent(lbl_codigoservico)
                            .addComponent(lbl_nomeservico))
                        .addGap(44, 44, 44)
                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodservico, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomeservico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodagendam, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_pesquisar)
                        .addGap(39, 39, 39)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addComponent(btn_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ultimo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_registro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_gravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)))
                .addGap(12, 12, 12))
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lbl_titulo))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scp_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sair1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_panel1Layout.setVerticalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbl_titulo)
                .addGap(53, 53, 53)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigoservico)
                    .addComponent(txtcodservico, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigotiposervico)
                    .addComponent(txttiposervico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigoagendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodagendam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeservico)
                    .addComponent(txtnomeservico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registro)
                    .addComponent(btn_gravar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_primeiro)
                    .addComponent(btn_anterior)
                    .addComponent(btn_proximo)
                    .addComponent(btn_ultimo))
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scp_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btn_sair1)))
                .addGap(49, 49, 49)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sair)
                    .addComponent(lbl_pesquisar)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_panel1);
        pnl_panel1.setBounds(30, 50, 810, 730);

        lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/backgroundlogin.png"))); // NOI18N
        getContentPane().add(lbl_imagem);
        lbl_imagem.setBounds(-10, -10, 1000, 840);

        setBounds(500, 50, 881, 839);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        txtcodservico.setText(""); // Limpa a caixa de texto em questão
        txttiposervico.setText("");
        txtcodagendam.setText("");
        txtnomeservico.setText("");
        txtcodservico.requestFocus(); // posiciona o cursor neste campo para digitação
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        String cod_servico = txtcodservico.getText();
        String tipo_servico = txttiposervico.getText();
        String cod_agendam = txtcodagendam.getText();
        String nome_servico = txtnomeservico.getText();


        try {
            String insert_sql="insert into servicos (Cod_TipoServico, Cod_Agendam, Nome_Servico) values ('" + tipo_servico + "','" + cod_agendam + "','" + nome_servico + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from servicos order by Cod_Servico");
            preencherTabela();

        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação : \n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        String cod_servico = txtcodservico.getText();
        String tipo_servico = txttiposervico.getText();
        String cod_agendam = txtcodagendam.getText();
        String nome_servico = txtnomeservico.getText();
        String sql;
        String msg="";

        try {
            if(txtcodservico.getText().equals("")){
                sql="insert into servicos (Cod_TipoServico, Cod_Agendam, Nome_Servico) values ('" + tipo_servico + "','" + cod_agendam + "','" + nome_servico + "')";
                msg="Gravação de um novo registro";
            }else{
                sql="update servicos set Cod_TipoServico='"+ tipo_servico + "', Cod_Agendam= '" + cod_agendam + "', Nome_Servico = '" + nome_servico + "' where Cod_Servico = " + txtcodservico.getText();
                msg="Alteração de registro";

            }
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Gravação realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from servicos order by Cod_Servico");
            preencherTabela();

        } catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação : \n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed
public void preencherTabela(){
    tblServicos.getColumnModel().getColumn(0).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(1).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(2).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(3).setPreferredWidth(150);
    
    
    DefaultTableModel modelo = (DefaultTableModel) tblServicos.getModel();
    modelo.setNumRows(0);
    
    try{
        con_cliente.resultset.beforeFirst();
        while(con_cliente.resultset.next())
            modelo.addRow(new Object[] {
                con_cliente.resultset.getString("Cod_Servico"),con_cliente.resultset.getString("Cod_TipoServico"), con_cliente.resultset.getString("Cod_Agendam"),con_cliente.resultset.getString("Nome_Servico")
            });
            }
        catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "\n Eerro ao listar dados da tabela!! :\n" + erro, "Mesangem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    


public void posicionarRegistro(){
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
        mostrar_Dados(); // chama o método que irá buscar o dado da tabela
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: " +erro, "Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}

public void mostrar_Dados(){
    try{
        txtcodservico.setText(con_cliente.resultset.getString("Cod_Servico"));
        txttiposervico.setText(con_cliente.resultset.getString("Cod_TipoServico")); 
        txtcodagendam.setText(con_cliente.resultset.getString("Cod_Agendam")); 
        txtnomeservico.setText(con_cliente.resultset.getString("Nome_Servico")); 
       
    
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
    }
}

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        String sql="";
        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ","Confirmar Exclusão",JOptionPane.YES_NO_OPTION,3);
            if(resposta == 0){
                sql="delete from servicos where Cod_Servico = " + txtcodservico.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if(excluir ==1){
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from servicos order by Cod_Servico");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!","Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }catch (SQLException excecao) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void tblServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMouseClicked
        // evento que sincroniza a grid com o mouse
        int linha_selecionada = tblServicos.getSelectedRow();
        txtcodservico.setText(tblServicos.getValueAt(linha_selecionada, 0).toString());
        txttiposervico.setText(tblServicos.getValueAt(linha_selecionada, 1).toString());
        txtcodagendam.setText(tblServicos.getValueAt(linha_selecionada, 2).toString());
        txtnomeservico.setText(tblServicos.getValueAt(linha_selecionada, 3).toString());
    }//GEN-LAST:event_tblServicosMouseClicked

    private void tblServicosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServicosKeyPressed
        // evento que sincroniza a grid com a setas do teclado
        int linha_selecionada = tblServicos.getSelectedRow();
        txtcodservico.setText(tblServicos.getValueAt(linha_selecionada, 0).toString());
        txttiposervico.setText(tblServicos.getValueAt(linha_selecionada, 1).toString());
        txtcodagendam.setText(tblServicos.getValueAt(linha_selecionada, 2).toString());
        txtnomeservico.setText(tblServicos.getValueAt(linha_selecionada, 3).toString());

    }//GEN-LAST:event_tblServicosKeyPressed

    private void btn_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeiroActionPerformed
        try {
            con_cliente.resultset.first();
            mostrar_Dados();
        }catch(SQLException erro){

        }
    }//GEN-LAST:event_btn_primeiroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        try {
            con_cliente.resultset.previous();
            mostrar_Dados();
        }catch(SQLException erro){

        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        try {
            con_cliente.resultset.next();
            mostrar_Dados();
        }catch(SQLException erro){

        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        try {
            con_cliente.resultset.last();
            mostrar_Dados();
        }catch(SQLException erro){

        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        try{
            String pesquisa = "select * from servicos where Nome_Servico like '" + txtpesquisar.getText()+ "%'";
            con_cliente.executaSQL(pesquisa);

            if(con_cliente.resultset.first()){
                preencherTabela();
            }
            else{
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!! :\n"+errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void btn_sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sair1ActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sair1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_primeiro;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_sair1;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JLabel lbl_codigoagendamento;
    private javax.swing.JLabel lbl_codigoservico;
    private javax.swing.JLabel lbl_codigotiposervico;
    private javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_nomeservico;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_panel1;
    private javax.swing.JScrollPane scp_tabela;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtcodagendam;
    private javax.swing.JLabel txtcodservico;
    private javax.swing.JTextField txtnomeservico;
    private javax.swing.JTextField txtpesquisar;
    private javax.swing.JTextField txttiposervico;
    // End of variables declaration//GEN-END:variables
}
