/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

import conexao.Conexao;
 
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.sql.*;
import javax.swing.table.DefaultTableModel;

public class Frm_ServicosCliente extends javax.swing.JInternalFrame {

    Conexao con_cliente;
    public Frm_ServicosCliente() {
        initComponents();
        con_cliente = new Conexao(); // inicialização do objeto como instância
        con_cliente.conecta(); // chama o método que conecta
        con_cliente.executaSQL("select * from servicos order by Cod_Servico");
        preencherTabela();
        posicionarRegistro();
        tblServicos.setAutoCreateRowSorter(true); // ativa a classificação ordenada da tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_panel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        scp_tabela = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        lbl_pesquisar = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        lbl_imagem = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2362, 1055));
        setMinimumSize(new java.awt.Dimension(2362, 1055));
        setPreferredSize(new java.awt.Dimension(2362, 1055));
        getContentPane().setLayout(null);

        pnl_panel1.setMinimumSize(new java.awt.Dimension(32767, 32767));
        pnl_panel1.setPreferredSize(new java.awt.Dimension(32767, 32767));

        lbl_titulo.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        lbl_titulo.setText("CONSULTA SERVIÇOS");

        btn_sair.setBackground(new java.awt.Color(153, 204, 255));
        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        tblServicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblServicos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Serviço", "Código Tipo Serviço ", "Código Agendamento", "Nome Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicosMouseClicked(evt);
            }
        });
        tblServicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblServicosKeyPressed(evt);
            }
        });
        scp_tabela.setViewportView(tblServicos);

        lbl_pesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_pesquisar.setText("Pesquisar por nome do serviço:");

        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_panel1Layout = new javax.swing.GroupLayout(pnl_panel1);
        pnl_panel1.setLayout(pnl_panel1Layout);
        pnl_panel1Layout.setHorizontalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                        .addComponent(scp_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_pesquisar)
                        .addGap(39, 39, 39)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        pnl_panel1Layout.setVerticalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lbl_titulo)
                .addGap(64, 64, 64)
                .addComponent(scp_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pesquisar)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(101, 101, 101))
        );

        getContentPane().add(pnl_panel1);
        pnl_panel1.setBounds(30, 50, 810, 590);

        lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/backgroundlogin.png"))); // NOI18N
        getContentPane().add(lbl_imagem);
        lbl_imagem.setBounds(-10, -10, 1000, 840);

        setBounds(500, 50, 881, 726);
    }// </editor-fold>//GEN-END:initComponents
public void preencherTabela(){
    tblServicos.getColumnModel().getColumn(0).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(1).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(2).setPreferredWidth(4);
    tblServicos.getColumnModel().getColumn(3).setPreferredWidth(150);
    
    
    DefaultTableModel modelo = (DefaultTableModel) tblServicos.getModel();
    modelo.setNumRows(0);
    
    try{
        con_cliente.resultset.beforeFirst();
        while(con_cliente.resultset.next())
            modelo.addRow(new Object[] {
                con_cliente.resultset.getString("Cod_Servico"),con_cliente.resultset.getString("Cod_TipoServico"), con_cliente.resultset.getString("Cod_Agendam"),con_cliente.resultset.getString("Nome_Servico")
            });
            }
        catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "\n Eerro ao listar dados da tabela!! :\n" + erro, "Mesangem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    


public void posicionarRegistro(){
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
       
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: " +erro, "Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}


    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void tblServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMouseClicked
        
    }//GEN-LAST:event_tblServicosMouseClicked

    private void tblServicosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServicosKeyPressed
       

    }//GEN-LAST:event_tblServicosKeyPressed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        try{
            String pesquisa = "select * from servicos where Nome_Servico like '" + txtpesquisar.getText()+ "%'";
            con_cliente.executaSQL(pesquisa);

            if(con_cliente.resultset.first()){
                preencherTabela();
            }
            else{
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!! :\n"+errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_panel1;
    private javax.swing.JScrollPane scp_tabela;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
