/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

/**
 *
 * @author Guilherme
 */
public class Frm_Creditos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Creditos
     */
    public Frm_Creditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_panel1 = new javax.swing.JPanel();
        lbl_titulocreditos = new javax.swing.JLabel();
        lbl_creditos1 = new javax.swing.JLabel();
        lbl_creditos2 = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        lbl_titulocreditos.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        lbl_titulocreditos.setText("CRÉDITOS");

        lbl_creditos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_creditos1.setText("Desenvolvido por Guilherme Lima de Paula ");

        lbl_creditos2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_creditos2.setText("para a disciplina de Desenvolvimento de Sistemas (DS), orientada pela professora Edna");

        btn_sair.setBackground(new java.awt.Color(153, 204, 255));
        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_panel1Layout = new javax.swing.GroupLayout(pnl_panel1);
        pnl_panel1.setLayout(pnl_panel1Layout);
        pnl_panel1Layout.setHorizontalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_creditos2))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lbl_creditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lbl_titulocreditos))
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl_panel1Layout.setVerticalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_titulocreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_creditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_creditos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnl_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnl_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setBounds(500, 50, 936, 619);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_creditos1;
    private javax.swing.JLabel lbl_creditos2;
    private javax.swing.JLabel lbl_titulocreditos;
    private javax.swing.JPanel pnl_panel1;
    // End of variables declaration//GEN-END:variables
}
