/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

import conexao.Conexao;
import conexao.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Guilherme
 */
public class Frm_Clientes extends javax.swing.JInternalFrame {

    Conexao con_cliente;
    
    public Frm_Clientes() {
        initComponents();
         con_cliente = new Conexao(); // inicialização do objeto como instância
        con_cliente.conecta(); // chama o método que conecta
        con_cliente.executaSQL("select * from cliente order by Cod_Cli");
        preencherTabela();
        posicionarRegistro();
        tblClientes.setAutoCreateRowSorter(true); // ativa a classificação ordenada da tabela
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_panel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_datanasc = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        lbl_telefone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txtCodTel = new javax.swing.JTextField();
        btn_registro = new javax.swing.JButton();
        btn_gravar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        scp_tabela = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btn_primeiro = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        lbl_telefone1 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        lbl_pesquisar = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        txtCod = new javax.swing.JLabel();
        lbl_imagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        lbl_titulo.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        lbl_titulo.setText("CADASTRO CLIENTES");

        lbl_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_codigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_codigo.setText("Código Cliente:");

        lbl_datanasc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_datanasc.setText("CPF:");

        lbl_telefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_telefone.setText("RG:");

        lbl_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_email.setText("Código Telefone:");

        btn_registro.setBackground(new java.awt.Color(153, 204, 255));
        btn_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registro.setText("Novo Registro");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        btn_gravar.setBackground(new java.awt.Color(153, 204, 255));
        btn_gravar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_gravar.setText("Gravar");
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });

        btn_alterar.setBackground(new java.awt.Color(153, 204, 255));
        btn_alterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(153, 204, 255));
        btn_excluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(153, 204, 255));
        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Data de Nascimento", "Código Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        scp_tabela.setViewportView(tblClientes);

        btn_primeiro.setBackground(new java.awt.Color(153, 204, 255));
        btn_primeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_primeiro.setText("Primeiro");
        btn_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeiroActionPerformed(evt);
            }
        });

        btn_anterior.setBackground(new java.awt.Color(153, 204, 255));
        btn_anterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_proximo.setBackground(new java.awt.Color(153, 204, 255));
        btn_proximo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_proximo.setText("Próximo");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        btn_ultimo.setBackground(new java.awt.Color(153, 204, 255));
        btn_ultimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ultimo.setText("Último");
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        lbl_telefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_telefone1.setText("Data de Nascimento");

        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });

        lbl_pesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_pesquisar.setText("Pesquisar por nome:");

        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_panel1Layout = new javax.swing.GroupLayout(pnl_panel1);
        pnl_panel1.setLayout(pnl_panel1Layout);
        pnl_panel1Layout.setHorizontalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_primeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_proximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ultimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_gravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluir)
                .addGap(21, 21, 21))
            .addGroup(pnl_panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addComponent(lbl_pesquisar)
                        .addGap(46, 46, 46)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scp_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_panel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_codigo)
                                            .addComponent(lbl_nome))
                                        .addGap(66, 66, 66)
                                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_telefone)
                                            .addComponent(lbl_telefone1)
                                            .addComponent(lbl_email))
                                        .addGap(35, 35, 35)
                                        .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodTel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtRG, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDataNasc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addGap(232, 232, 232))
        );
        pnl_panel1Layout.setVerticalGroup(
            pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_titulo)
                .addGap(37, 37, 37)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_panel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_codigo)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_panel1Layout.createSequentialGroup()
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefone)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txtCodTel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefone1)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registro)
                    .addComponent(btn_gravar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_primeiro)
                    .addComponent(btn_anterior)
                    .addComponent(btn_proximo)
                    .addComponent(btn_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scp_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pesquisar)
                    .addComponent(btn_sair))
                .addGap(18, 18, 18))
        );

        getContentPane().add(pnl_panel1);
        pnl_panel1.setBounds(40, 10, 840, 750);

        lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/backgroundlogin.png"))); // NOI18N
        lbl_imagem.setText("jLabel1");
        getContentPane().add(lbl_imagem);
        lbl_imagem.setBounds(-210, -170, 2540, 1130);

        setBounds(500, 50, 938, 826);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        String sql="";
        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ","Confirmar Exclusão",JOptionPane.YES_NO_OPTION,3);
            if(resposta == 0){
                sql="delete from cliente where Cod_Cli = " + txtCod.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if(excluir ==1){
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from cliente order by Cod_Cli");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!","Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }catch (SQLException excecao) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed
public void preencherTabela(){
    tblClientes.getColumnModel().getColumn(0).setPreferredWidth(4);
    tblClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
    tblClientes.getColumnModel().getColumn(2).setPreferredWidth(20);
    tblClientes.getColumnModel().getColumn(3).setPreferredWidth(20);
    tblClientes.getColumnModel().getColumn(4).setPreferredWidth(4);
    tblClientes.getColumnModel().getColumn(5).setPreferredWidth(30);
    
    DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
    modelo.setNumRows(0);
    
    try{
        con_cliente.resultset.beforeFirst();
        while(con_cliente.resultset.next())
            modelo.addRow(new Object[] {
                con_cliente.resultset.getString("Cod_Cli"),con_cliente.resultset.getString("Nome"), con_cliente.resultset.getString("CPF"),con_cliente.resultset.getString("RG"), con_cliente.resultset.getString("Cod_TelefoneCli"), con_cliente.resultset.getString("DataNasc")
            });
            }
        catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "\n Eerro ao listar dados da tabela!! :\n" + erro, "Mesangem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    


public void posicionarRegistro(){
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
        mostrar_Dados(); // chama o método que irá buscar o dado da tabela
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: " +erro, "Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}

public void mostrar_Dados(){
    try{
        txtCod.setText(con_cliente.resultset.getString("Cod_Cli")); // Associar a caixa de texto ao campo cod
        txtNome.setText(con_cliente.resultset.getString("Nome")); // Associar a caixa de texto ao campo nome
        txtCPF.setText(con_cliente.resultset.getString("CPF")); // Associar a caixa de texto ao campo data de nascimento
        txtRG.setText(con_cliente.resultset.getString("RG")); // Associar a caixa de texto ao campo telefone
        txtCodTel.setText(con_cliente.resultset.getString("Cod_TelefoneCli")); // Associar a caixa de texto ao campo email
         txtDataNasc.setText(con_cliente.resultset.getString("DataNasc")); // Associar a caixa de texto ao campo email
    
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
    }
    
}
    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        String Nome = txtNome.getText();
        String CPF = txtCPF.getText();
        String RG = txtRG.getText();
        String CodTelefoneCli = txtCodTel.getText();
        String DataNasc = txtCodTel.getText();
        String sql;
        String msg="";

        try {
            if(txtCod.getText().equals("")){
                sql="insert into cliente (Nome, CPF, RG, Cod_TelefoneCli, DataNasc) values ('" + Nome + "','" + CPF + "','" + RG + "','" + CodTelefoneCli + "','" + DataNasc + "')";
                msg="Gravação de um novo registro";
            }else{
                sql="update cliente set Nome='" + Nome + "',CPF='"+ CPF + "', RG = '" + RG + "', Cod_TelefoneCli = '" + CodTelefoneCli + "', DataNasc = '" + DataNasc + "'where Cod_Cli= " + txtCod.getText();
                msg="Alteração de registro";

            }
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Gravação realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from cliente order by Cod_Cli");
            preencherTabela();

        } catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação : \n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        String Nome = txtNome.getText();
        String CPF = txtCPF.getText();
        String RG = txtRG.getText();
        String CodTelefoneCli = txtCodTel.getText();
        String DataNasc = txtCodTel.getText();

        try {
            String insert_sql="insert into cliente (Nome, CPF, RG, Cod_TelefoneCli, DataNasc) values ('" + Nome + "','" + CPF + "','" + RG + "','" + CodTelefoneCli + "','" + DataNasc + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from cliente order by Cod_Cli");
            preencherTabela();

        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação : \n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        txtCod.setText(""); // Limpa a caixa de texto em questão
        txtNome.setText("");
        txtCPF.setText("");
        txtRG.setText("");
        txtCodTel.setText("");
        txtDataNasc.setText("");
        txtCod.requestFocus(); // posiciona o cursor neste campo para digitação
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // evento que sincroniza a grid com o mouse
        int linha_selecionada = tblClientes.getSelectedRow();
        txtCod.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        txtCPF.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        txtRG.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        txtCodTel.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
        txtDataNasc.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        // evento que sincroniza a grid com a setas do teclado
        int linha_selecionada = tblClientes.getSelectedRow();
        txtCod.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        txtCPF.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        txtRG.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        txtCodTel.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
        txtDataNasc.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_tblClientesKeyPressed

    private void btn_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeiroActionPerformed
        try {
            con_cliente.resultset.first();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_primeiroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        try {
            con_cliente.resultset.previous();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        try {
            con_cliente.resultset.next();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        try {
            con_cliente.resultset.last();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do Programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
         try{
            String pesquisa = "select * from cliente where Nome like '" + txtpesquisar.getText()+ "%'";
            con_cliente.executaSQL(pesquisa);

            if(con_cliente.resultset.first()){
                preencherTabela();
            }
            else{
                JOptionPane.showMessageDialog(null, "\n Não existe dados com este paramêtro!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!! :\n"+errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_primeiro;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_datanasc;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JLabel lbl_telefone1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_panel1;
    private javax.swing.JScrollPane scp_tabela;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JLabel txtCod;
    private javax.swing.JTextField txtCodTel;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
